---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: docker.io/mysql:8.0.22
        env:
         - name: MYSQL_ROOT_PASSWORD
           value: debezium
         - name: MYSQL_USER
           value: debezium
         - name: MYSQL_PASSWORD
           value: debezium
         - name: MYSQL_DATABASE
           value: inventory
        ports:
        - containerPort: 3306
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
